;; Auto generated by `pyim-generate-dict-cache-file', don't edit it by hand!

#s(hash-table size 1000000 test equal rehash-size 1.5 rehash-threshold 0.8 data ("cha-zhao" ("查找") "c-z" ("查找") "chong-fu" ("重复") "c-f" ("重复") "ji-lu" ("纪录") "j-l" ("纪录")))
